---
title: "Home"
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

## Implementation Checks.

* [In matrix case, homoscedastic tflash gives same results as flash. Looks fine in tensor case.](check_tflash.pdf)
* [In matriix case, greedy algorithm of tflash same as in flash. Looks fine in tensor case.](check_greedy_tflash.pdf)
* [Backfitting tflash gives reasonable results.](check_backfitting.pdf)
* [Kronecker structured variance gives reasonable estimates, indicating implementation is correct.](check_kronecker.pdf)
* [flash runs about twice as fast as tflash.](speed_comparison.html)
* [Justification for using first singular vectors as starting values.](starting_value_influence.html) Even when starting in random directions, posterior estimates only ever end up at near the first singular vectors or all shrunk to zero.
* [The posterior mean estimates and the empirical singular vectors are super close to each other.](starting_value_sim.html)

## Early simulations to see if I get reasonable answers.

* [All null Kronecker structured variance setting. FLASH works pretty well setting components to zero and estimating variances. Does better as dimension increases.](all_null.pdf)
* [Updating the missing data during each variational update is better than just inserting zeros.](missing_data.pdf)
* [Another missing example where imputing zeros is very bad.](another_missing_example.html)
* [T-FLASH performs better than the least-squares estimator and an estimator of the Hoff](early_comparisons.pdf)

## Factor Analyses
* [My first attempt at fitting T-FLASH to the GTEX data.](first_analysis.html) I think I need to fix my language. E.g. I am really lax about the definitions of factors and components and loading on something. Overall, I found some interpretable components.